name: psn.hotels.hub
description: The PSN Hotels application is your indispensable tool for working with hotel photos. Designed specifically for managers of the “Come with us” travel network, this application allows you not only to conveniently store all the necessary photos and video materials in one place, but also to effectively share them through social networks and instant messengers.

publish_to: 'none'
version: 1.25.9+49

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  workmanager:
    git:
      url: https://github.com/absar/flutter_workmanager.git
      ref: ios-bg-tasks-enh-final

  webview_flutter: ^4.5.0
  #database
  sqflite: ^2.3.2

  image_cropper: ^4.0.1

  share_plus: ^9.0.0

  reflectable: any
  pretty_dio_logger: ^1.1.1
  #cached_network_image: ^3.3.1
  shared_preferences: ^2.0.13
  flutter_bloc: ^8.0.1
  dart_json_mapper_flutter: ^2.0.1

  location: ^5.0.3
  geolocator: ^10.1.0
  equatable: ^2.0.3
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0
  
  #for checking internet connection
  connectivity_plus: ^5.0.2

  #camera
  camera: ^0.10.5+9
  camera_android_camerax: ^0.6.3
  video_compress: ^3.1.0
  photo_view: ^0.14.0
  chewie: ^1.3.0
  video_player: ^2.8.4
  permission_handler: ^11.2.0
  app_settings: ^5.1.1
  gallery_saver: ^2.3.2
  open_file: ^3.3.2
  sensors: ^2.0.3

  percent_indicator: ^4.0.0
  
  package_info: ^2.0.2

  cupertino_icons: ^1.0.0

  connectivity_plus_web: ^1.2.5
  wakelock_web: ^0.4.0
  #for actions with items in lists
  flutter_slidable: ^3.1.0

#analytic and crashlytics
  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.4.18
  firebase_core: ^2.27.0

  app_tracking_transparency: ^2.0.4
  flutter_svg: ^2.0.9
  image_picker: ^1.0.8
  device_info_plus: ^10.1.0
  app_version_update: ^3.1.0
  
  

dev_dependencies:
 build_runner: ^2.4.7
 flutter_launcher_icons: ^0.13.1
 flutter_native_splash: ^2.1.0

flutter_icons:
  image_path: "assets/app/icon_launcher.jpg"
  android: true
  ios: true


flutter:

  assets:
    - assets/icons/

  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: fonts/SFUIDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFUIDisplay-Heavy.ttf
          weight: 800
        - asset: fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFUIDisplay-Regular.ttf
        - asset: fonts/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFUIDisplay-Thin.ttf
          weight: 100
        - asset: fonts/SFUIDisplay-Ultralight.ttf
          weight: 200
        
  uses-material-design: true


flutter_native_splash:
  background_image: assets/app/background_image_splash_screen.jpg
  fullscreen: true