name: Production CD (App Store & Play Market)

on:
  push:
    branches: [ main ]

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create Firebase Config (Android)
        run: echo '${{ secrets.ANDROID_GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - name: Create Firebase Config (iOS)
        run: echo '${{ secrets.IOS_GOOGLE_SERVICES_PLIST }}' > ios/Runner/GoogleService-Info.plist

      - name: Decode Android Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Build Android AppBundle
        run: |
          NEW_BUILD_NUMBER=$((55 + ${{ github.run_number }}))
          flutter build appbundle --release --build-number $NEW_BUILD_NUMBER

      - name: Upload to Play Store (Production)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
          packageName: psn.hotels.app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production

  deploy-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Create Firebase Config (iOS)
        run: echo '${{ secrets.IOS_GOOGLE_SERVICES_PLIST }}' > ios/Runner/GoogleService-Info.plist

      - name: Install Apple Certificate
        uses: Apple-Actions/import-codesigning-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_P12_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}

      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS IPA
        run: |
          NEW_BUILD_NUMBER=$((55 + ${{ github.run_number }}))
          flutter build ipa --release --build-number $NEW_BUILD_NUMBER \
          --export-options-plist=ios/ExportOptions.plist \
          --build-name=1.26.2

      - name: Upload to App Store
        uses: Apple-Actions/upload-testflight-build@v1
